---
title: "Resumo de Valoração"
author: "Projeto Boto-Cinza --- IPeC"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---


```{r setup, include=FALSE}
atualiza_bruto <- FALSE
atualiza_fino <- FALSE
```

```{r dados_banco, include=FALSE}
library(kableExtra)
source("01_scripts/bd_banco.R")

# Definindo caminhos
pasta_outputs <- file.path(rprojroot::find_rstudio_root_file(), "03_results")

bd <- bd_banco(pasta_outputs, update_bruto = atualiza_bruto, update_fino = atualiza_fino)
```

Tabelas
===================================== 

Row {.tabset .tabset-pills}
-----------------------------------------------------------------------

### Perguntas
```{r}
bd$perguntas[1:10,] %>%
  kbl() %>%
  kable_classic(c("hover")) %>%
  scroll_box(height = "100%")
```

### Entrevistas
```{r}
bd$entrevistas[1:10,] %>%
  kbl() %>%
  kable_classic(c("hover")) %>%
  scroll_box(height = "100%")
```

### Respostas
```{r}
bd$respostas[1:10,] %>%
  kbl() %>%
  kable_classic(c("hover")) %>%
  scroll_box(height = "100%")
```

- Preparar val_